# Generated by Django 4.2.2 on 2023-06-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(default='Others', max_length=30),
        ),
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
