# Generated by Django 4.2.2 on 2023-06-24 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='date',
        ),
        migrations.AddField(
            model_name='budget',
            name='month',
            field=models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('user', 'month'), name='unique_budget_per_user_month'),
        ),
    ]
