# Generated by Django 4.2.2 on 2023-06-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='starting_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
