# Generated by Django 4.2.2 on 2023-06-21 06:15

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_alter_user_starting_amt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='starting_amt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
